version: '3'
services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - 8082:8080

  redis:
    image: redis
    ports:
      - '6379:6379'

  pgsql:
    image: postgres
    command:
      - "postgres"
      - "-c"
      - "config_file=/etc/postgresql/postgresql.conf"
    volumes:
      - ./docker/pgsql/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "user"
      POSTGRES_DB: "vote"
    ports:
      - '5432:5432'

  adminer:
    image: adminer
    depends_on:
      - pgsql
    ports:
      - '8081:8080'